module config

export TORC_SERVER_TAG, TORC_STEAL_RESPONSE_TAG, TORC_ARGS_RESPONSE_TAG, TORC_TASK_YIELDTIME, TORC_QUEUE_LEVELS, TORC_RESPONSE_BASE

const TORC_SERVER_TAG::UInt = 100
const TORC_STEAL_RESPONSE_TAG::UInt = 101
const TORC_TASK_YIELDTIME::Float64 = 0.0001
const TORC_QUEUE_LEVELS::UInt = 10

end